
Organizations:
#######List-Start
    - &-OrderIDForReplace-
        Name: -OrderIDForReplace-
        ID: -OrderIDForReplace-
        MSPDir: -ProjectDIR-/crypto-config/ordererOrganizations/-DomainForReplace-/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('-OrderIDForReplace-.member')"
            Writers:
                Type: Signature
                Rule: "OR('-OrderIDForReplace-.member')"
            Admins:
                Type: Signature
                Rule: "OR('-OrderIDForReplace-.admin')"
#######List-End

#######List-Start
    - &-OrgIDForReplace-
        Name: -OrgIDForReplace-
        ID: -OrgIDForReplace-
        MSPDir: -ProjectDIR-/crypto-config/peerOrganizations/-OrgIDForReplace-.-DomainForReplace-/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('-OrgIDForReplace-.admin', '-OrgIDForReplace-.peer', '-OrgIDForReplace-.client')"
            Writers:
                Type: Signature
                Rule: "OR('-OrgIDForReplace-.admin', '-OrgIDForReplace-.client')"
            Admins:
                Type: Signature
                Rule: "OR('-OrgIDForReplace-.admin')"

        AnchorPeers:
            - Host: -AnchorIpForReplace-
              Port: -AnchorPortForReplace-
#######List-End

Capabilities:
    Channel: &ChannelCapabilities
        V1_3: true
    Orderer: &OrdererCapabilities
        V1_1: true
    Application: &ApplicationCapabilities
        V1_3: true
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: kafka
    Addresses:
#######OrderList-Start
        - -OrderIDForReplace-.-DomainForReplace-:-OrderPortForReplace-
#######OrderList-End

    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Kafka:
        Brokers:
            - kafka0.-DomainForReplace-:9092
            - kafka1.-DomainForReplace-:9192
            - kafka2.-DomainForReplace-:9292
            - kafka3.-DomainForReplace-:9392

    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    ProjectOrgsChannel:
        Consortium: KafkaConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
#######List-Start
                - *-OrgIDForReplace-
#######List-End
            Capabilities:
                <<: *ApplicationCapabilities

    SampleDevModeKafka:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: kafka
            Kafka:
                Brokers:
                  - kafka0.-DomainForReplace-:9092
                  - kafka1.-DomainForReplace-:9192
                  - kafka2.-DomainForReplace-:9292
                  - kafka3.-DomainForReplace-:9392

            Organizations:
#######List-Start
                - *-OrderIDForReplace-
#######List-End
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
#######List-Start
                - <<: *-OrderIDForReplace-
#######List-End
        Consortiums:
            SampleConsortium:
                Organizations:
#######List-Start
                    - *-OrgIDForReplace-
#######List-End

